### ISSUE TITLE
Setup requirments is missing from deployment

### ISSUE THREAD

**Issue by jhagberg** [neicnordic/sftpbeamer#1]
In the deployment guide https://github.com/neicnordic/sftpbeamer/blob/master/DEPLOYMENT.md
The setup of the requirments is missing
https://github.com/neicnordic/sftpbeamer/blob/master/requirements.txt

I am also missing suggestions on OS. what brands of linux have you tested this and what is the recommendation?

**Comment by xiaxi-li** [comment]
I created another branch pull-request-branch and sent a pull request to you.
